version: '3.6'
services:
    app:
        image: project-image
        container_name: project-container
        build:
            context: .
        ports:
            - "8080:8080"
        environment:
            DB_URL: jdbc:postgresql://postgres:5432/bestProject
            RABBIT_HOST: rabbitmq
            PORT: 8080
        deploy:
            restart_policy:
                delay: 5s
                condition: on-failure
                max_attempts: 5

        networks:
            - backend

    postgres:
        image: 'postgres:15.2-alpine'
        container_name: postgres
        ports:
            - "5433:5432"

        environment:
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=farmProject
        restart: always
        networks:
            - backend
        volumes:
            - ./volume/postgres_data:/var/lib/postgresql/data/

    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: username
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./volume/rabbitmq_data:/var/lib/rabbitmq
networks:
    backend: {}