version: '3.6'
services:
    app:
        image: project-image
        container_name: project-container
        build:
            context: .
        ports:
            - "8080:8080"
        environment:
            DB_URL: jdbc:postgresql://localhost:5433/farmProject
            RABBIT_HOST: localhost
            PORT: 8080
        deploy:
            restart_policy:
                delay: 5s
                condition: on-failure
                max_attempts: 5

        networks:
            - backend
networks:
    backend: {}